services:
  back:
    command: dotnet run --urls http://0.0.0.0:5000
    image: mcr.microsoft.com/dotnet/sdk
    ports:
      - 5000:5000
    volumes:
      - ./Back:/app
    working_dir: /app

  front:
    command: sh -c "npm install && npm start -- --host 0.0.0.0"
    depends_on:
      - back
    image: node
    ports:
      - 4200:4200
    volumes:
      - ./Desarrollo:/app
    working_dir: /app
